name: timothyhoward
favicon: null
layout_spectrum: 0.08234337903559208
typography_spectrum: 0.7415687860921025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.383529104758054
  lightness: 0.9687276906333864
  saturation: 0.11777345975860953
  rhythmicContrast: 0.6115544375497848
purpose: []
