name: Timothy Howard
favicon: null
layout_spectrum: 0.3941
typography_spectrum: 0.3848
title: Timothy Howard
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#1d140f'
    - '#6d8283'
    - '#a0bac9'
    - '#cc3440'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
